DETECTOR_ITERATIONS = "detector_iterations"
FREQUENCY_CHANGES_PER_DEGREE = "frequency_change_per_degree"
INTERMISSION_COUNTDOWN = "intermission_countdown"
START_COUNTDOWN = "start_countdown"
TUNER_ITERATIONS = "tuner_iterations"
TUNING_EPSILON = "tuning_epsilon"
